alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dcps='docker-compose ps'
alias dcl='docker-compose logs'
alias dclf='docker-compose logs -f'
alias dcr='docker-compose run --rm'

alias dps='docker ps'
alias dv='docker volume'
