set-option -g default-shell /usr/bin/zsh

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# sane window split defaults
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# shortcut to source the .tmux.conf file
bind R source-file ~/.tmux.conf \; display "~/.tmux.conf reloaded"

# moving around panes like vim
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# resizing panes
bind K resize-pane -U 4 
bind J resize-pane -D 4
bind H resize-pane -L 4
bind L resize-pane -R 4

# don't rename windows automatically
set-option -g allow-rename off
