alias v='nvim'
alias vim='nvim'
alias szsh='source ${HOME}/.zshrc'
alias -g kssh='kitty +kitten ssh'
alias ksw='kitty @ new-window --no-response --cwd `pwd`'
alias kfs='kitty @ set-font-size'
alias kcw='kitty @ close-window --self'
alias kwt='kitty @ set-window-title'
alias ktt='kitty @ set-tab-title'

# Git aliases
alias gco='git checkout'
alias gst='git status'
alias gpu='git push'
alias gpl='git pull'
