local kind = {
  Text = "",
  Method = "m",
  Function = "",
  -- Constructor = "",
  -- Method = "",
  -- Function = "",
  Constructor = "",
  Field = "",
  -- Variable = "",
  Variable = "",
  Class = "",
  Interface = "",
  -- Module = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  -- Keyword = "",
  Snippet = "",
  -- Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}

local git = {
  Add = "",
  Mod = "",
  Remove = "",
  Ignore = "",
  Rename = "",
  Diff = "",
  Repo = "",
  Octoface = "",
}

return {
  kind = kind,
  git = git,
}
